# Generated by Django 4.2.1 on 2023-05-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='controlModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppta', models.CharField(blank=True, max_length=100)),
                ('fecha', models.CharField(blank=True, max_length=50)),
                ('aspirante', models.CharField(blank=True, max_length=250)),
                ('categoria', models.CharField(blank=True, max_length=250)),
                ('propone', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=250)),
                ('zona', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'controlTable',
            },
        ),
    ]
