# Generated by Django 4.2.1 on 2023-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlanaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmodel',
            name='fecha',
            field=models.DateField(blank=True, max_length=50),
        ),
    ]
