# Generated by Django 4.2.1 on 2023-05-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlanaa', '0002_alter_controlmodel_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmodel',
            name='fecha',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
